window.BUSINESS_CATALOG = [
  {
    id: "frozen-food",
    name: "Comidas congeladas listas para la semana",
    category: "Alimentos desde casa",
    summary: "Preparar porciones congeladas de comidas familiares y venderlas por pedido a hogares ocupados.",
    potential: "Resuelve ahorro de tiempo y alimentacion practica. Puede empezar con preventa, evitando desperdicio e inventario excesivo.",
    trend: "Demanda recurrente de conveniencia local; se fortalece con catalogos por WhatsApp y entrega programada.",
    skills: ["cooking"],
    format: ["home", "both"],
    devices: ["phone", "internet"],
    budgetMin: 70,
    professionalBudget: 520,
    hoursMin: 10,
    risk: "low",
    difficulty: "Inicial",
    launch: "7-10 dias",
    automation: 55,
    extra: true,
    scalable: true,
    revenue: { units: 70, price: 5.5, unitCost: 2.7, fixed: 30 },
    clients: "Familias con poco tiempo, trabajadores y personas mayores que quieren porciones sencillas.",
    investment: [
      "Ingredientes para prueba de 25 porciones: USD 55-75",
      "Envases aptos para congelar y etiquetas: USD 15-25",
      "Termometro, higiene y conservacion: USD 10-25",
      "Usar congelador existente primero; comprar equipo solo tras demanda confirmada"
    ],
    tools: ["Cocina higienica y congelador", "Envases rotulados con fecha y alergenos", "WhatsApp Business", "Hoja de costos"],
    process: [
      "Pregunta a 15 vecinos o contactos que comidas comprarian y a que precio.",
      "Ofrece una preventa de 3 platos y cobra antes de producir el lote.",
      "Cocina, enfria rapidamente, porciona, rotula y congela manteniendo normas locales.",
      "Entrega pedidos, recopila calificacion y mide recompra antes de ampliar sabores."
    ],
    recipe: {
      title: "Base de lasana de pollo y vegetales, 10 porciones",
      lines: ["1.2 kg pollo cocido desmenuzado, 1 kg vegetales, salsa de tomate, laminas y queso.", "Cocinar relleno; armar en envases de 450 g; hornear; enfriar y congelar rotulado.", "Costo ilustrativo USD 2.60-3.10 por porcion; probar venta USD 5.50-7.00 segun mercado."],
      safety: "La conservacion, alergenos, permisos y temperaturas deben verificarse con autoridad sanitaria local antes de vender."
    },
    suppliers: "Mercados mayoristas locales, distribuidor de envases grado alimentario y supermercados para el lote piloto. Comparar tres cotizaciones del pais del usuario.",
    branding: { names: ["CasaLista", "Congela & Sirve", "Semana Sabrosa"], slogan: "Tu comida real, lista cuando la necesitas.", colors: "Verde salvia, crema y coral" },
    automationIdeas: ["Catalogo y respuestas rapidas en WhatsApp Business", "Formulario de preventa con cupos", "IA para variar copies y calcular lista semanal, siempre revisada"],
    errors: ["Comprar congelador antes de validar pedidos", "No registrar costo por porcion", "Ignorar higiene, permisos o cadena fria"],
    growth: ["Semana 1: 10 compradores de prueba", "Mes 2: menu semanal por suscripcion", "Mes 3: alianzas con oficinas o condominios; evaluar cocina habilitada"],
    comparable: "Modelos similares: meal prep local por encargo y cocinas de suscripcion; validar competidores cercanos y sus precios."
  },
  {
    id: "senior-companion",
    name: "Acompanamiento practico para adultos mayores",
    category: "Servicio local humano",
    summary: "Visitas de acompanamiento no medico, compras, tecnologia basica y comunicacion con familiares.",
    potential: "El envejecimiento aumenta necesidades de apoyo cotidiano; el valor depende de confianza, referencias y limites claros.",
    trend: "Los roles de cuidado figuran entre ocupaciones con crecimiento esperado hacia 2030 segun WEF 2025.",
    skills: ["care"],
    format: ["home", "both"],
    devices: ["phone"],
    budgetMin: 20,
    professionalBudget: 180,
    hoursMin: 6,
    risk: "low",
    difficulty: "Inicial con responsabilidad",
    launch: "5-14 dias",
    automation: 30,
    extra: true,
    scalable: true,
    revenue: { units: 25, price: 13, unitCost: 2, fixed: 18 },
    clients: "Familiares que trabajan y necesitan acompanamiento confiable para un adulto mayor.",
    investment: ["Verificacion de antecedentes o referencias segun pais: variable", "Transporte inicial: USD 15-40", "Identificacion, libreta y material informativo: USD 5-15"],
    tools: ["Celular", "Protocolo de emergencia", "Agenda compartida autorizada", "Referencias verificables"],
    process: ["Define servicios permitidos: compania, recados y ayuda digital; excluye actos medicos.", "Consulta regulaciones, seguro y consentimiento requeridos en tu pais.", "Consigue dos referencias y ofrece una primera visita acompanada.", "Entrega reporte breve a la familia con autorizacion del adulto mayor."],
    suppliers: "Centros comunitarios, redes vecinales y profesionales de salud solo como fuentes de referencia, sin afirmar convenios.",
    branding: { names: ["Cerca de Ti", "Tiempo Sereno", "Manos Cercanas"], slogan: "Compania respetuosa, tranquilidad familiar.", colors: "Azul sereno, arena y verde" },
    automationIdeas: ["Recordatorios de visita", "Plantilla de reporte autorizada", "Calendario compartido sin almacenar informacion sensible innecesaria"],
    errors: ["Presentarse como cuidador medico sin acreditacion", "No acordar limites y emergencias", "Compartir datos personales sin permiso"],
    growth: ["Primer mes: tres familias recurrentes", "Crear capacitacion en trato y seguridad", "Contratar solo con protocolos y verificacion"],
    comparable: "Modelos similares: servicios de companionship no clinico y apoyo de diligencias; comprobar reglas locales.",
  },
  {
    id: "cleaning",
    name: "Limpieza profunda por reserva digital",
    category: "Servicios del hogar",
    summary: "Servicio enfocado en limpiezas puntuales para hogares, apartamentos de alquiler u oficinas pequenas.",
    potential: "Necesidad clara, resultado visible y cobro rapido. La diferenciacion esta en puntualidad, checklist y confianza.",
    trend: "Los servicios locales pueden captar demanda mediante resenas, mapas, grupos vecinales y WhatsApp.",
    skills: ["cleaning"],
    format: ["home", "both"],
    devices: ["phone"],
    budgetMin: 45,
    professionalBudget: 310,
    hoursMin: 8,
    risk: "low",
    difficulty: "Inicial",
    launch: "3-7 dias",
    automation: 45,
    extra: true,
    scalable: true,
    revenue: { units: 12, price: 45, unitCost: 10, fixed: 35 },
    clients: "Hogares ocupados, anfitriones de alquiler temporal y oficinas pequenas.",
    investment: ["Productos y guantes: USD 25-45", "Transporte: USD 10-30", "Fotos, perfil y tarjetas digitales: USD 0-10"],
    tools: ["Equipo de limpieza basico", "Checklist antes/despues", "WhatsApp Business", "Medio de pago local"],
    process: ["Elige un servicio muy concreto y tarifa por tamano.", "Realiza dos trabajos piloto autorizados para obtener fotos y resenas.", "Publica paquetes y disponibilidad semanal.", "Pide recompra o referidos tras cada entrega."],
    suppliers: "Mayoristas de productos de limpieza y ferreterias locales; confirmar fichas de seguridad y costos en la zona.",
    branding: { names: ["Brillo Puntual", "Orden Vivo", "Limpio Ya"], slogan: "Llegamos, cumplimos, se nota.", colors: "Turquesa, blanco y azul" },
    automationIdeas: ["Reservas con formulario", "Recordatorios automaticos", "IA para textos de anuncio y respuestas frecuentes"],
    errors: ["Cobrar sin calcular transporte", "Usar productos inadecuados para superficies", "No documentar alcance del trabajo"],
    growth: ["Paquetes quincenales", "Servicio para alquileres con checklist", "Equipo capacitado y asegurado"],
    comparable: "Modelos similares: limpieza residencial por cita y turnovers para alquileres."
  },
  {
    id: "ai-automation",
    name: "Microagencia de automatizacion para comercios",
    category: "Servicio digital con IA",
    summary: "Configurar respuestas, catalogos, captura de prospectos y contenido asistido por IA para negocios pequenos.",
    potential: "Muchos comercios necesitan ahorrar tiempo pero requieren soluciones simples, medibles y acompanamiento humano.",
    trend: "El WEF 2025 indica que la IA y alfabetizacion tecnologica crecen en relevancia y que empresas buscan oportunidades con IA.",
    skills: ["digital"],
    format: ["digital", "both"],
    devices: ["phone", "internet", "computer"],
    budgetMin: 35,
    professionalBudget: 380,
    hoursMin: 12,
    risk: "medium",
    difficulty: "Intermedia",
    launch: "14-21 dias",
    automation: 90,
    extra: true,
    scalable: true,
    revenue: { units: 3, price: 190, unitCost: 25, fixed: 35 },
    clients: "Restaurantes, salones, agentes y tiendas que pierden consultas o publican sin constancia.",
    investment: ["Dominio o portafolio: USD 0-20", "Herramientas piloto: USD 0-35/mes", "Capacitacion y pruebas: tiempo propio"],
    tools: ["Computadora e internet estable", "WhatsApp Business", "Formularios/hojas", "Plataforma IA con politicas de privacidad"],
    process: ["Entrevista cinco comercios y detecta una tarea repetitiva.", "Crea demostracion sin datos sensibles: respuestas, leads o calendario de posts.", "Vende un piloto de dos semanas con indicador definido.", "Mide tiempo ahorrado o consultas respondidas; solo entonces amplifica."],
    suppliers: "Herramientas oficiales de mensajeria, automatizacion e IA; revisar precios, privacidad y terminos antes de revender.",
    branding: { names: ["Turno Automato", "Pulso Pyme AI", "Respuesta Clara"], slogan: "Menos tareas repetidas, mas clientes atendidos.", colors: "Azul noche, verde electrico y hielo" },
    automationIdeas: ["Clasificacion de preguntas frecuentes", "Borradores de contenido con aprobacion humana", "Reporte semanal de consultas y conversiones"],
    errors: ["Prometer ventas garantizadas", "Automatizar mensajes invasivos", "Enviar datos del cliente a IA sin consentimiento"],
    growth: ["Un nicho y un caso documentado", "Paquetes recurrentes por soporte", "Plantillas y formacion para equipos"],
    comparable: "Modelos similares: consultorias no-code para pequenas empresas y agencias de CRM conversacional."
  },
  {
    id: "tutoring",
    name: "Tutoria practica digital o local",
    category: "Educacion",
    summary: "Clases cortas de ingles, tareas escolares o habilidades digitales con acompanamiento semanal.",
    potential: "Se vende por resultado observable y referencias; inicia sin inventario y puede combinar presencial con video.",
    trend: "Educacion y recapacitacion son necesidades destacadas ante el cambio de habilidades previsto hacia 2030.",
    skills: ["teaching", "digital"],
    format: ["digital", "home", "both"],
    devices: ["phone", "internet"],
    budgetMin: 10,
    professionalBudget: 160,
    hoursMin: 6,
    risk: "low",
    difficulty: "Inicial",
    launch: "3-10 dias",
    automation: 50,
    extra: true,
    scalable: true,
    revenue: { units: 22, price: 12, unitCost: 1, fixed: 10 },
    clients: "Estudiantes, adultos que buscan empleabilidad o mayores que requieren ayuda digital.",
    investment: ["Materiales y conectividad: USD 0-15", "Publicidad de prueba: USD 0-20", "Videollamada gratuita inicialmente"],
    tools: ["Celular o computadora", "Video llamada", "Guia de clase", "Evaluacion simple"],
    process: ["Selecciona un resultado que puedas ensenar honestamente.", "Ofrece sesion diagnostica corta a cinco contactos.", "Arma paquete de cuatro clases con objetivo medible.", "Recopila progreso y referencias con permiso."],
    suppliers: "Plataformas gratuitas de videollamada y materiales legales o propios; no copiar cursos protegidos.",
    branding: { names: ["Paso Claro", "Aprende Cerca", "Habilidad Ya"], slogan: "Aprender para usarlo esta semana.", colors: "Indigo, amarillo y blanco" },
    automationIdeas: ["Agenda y recordatorios", "IA para ejercicios adaptados revisados por el tutor", "Resumen de progreso"],
    errors: ["Ensenar una materia no dominada", "No medir progreso", "Usar material sin licencia"],
    growth: ["Grupos pequenos", "Curso grabado complementario", "Especializacion por perfil laboral"],
    comparable: "Modelos similares: tutores por videollamada y talleres comunitarios de alfabetizacion digital."
  },
  {
    id: "print-crafts",
    name: "Regalos personalizados bajo pedido",
    category: "Producto creativo",
    summary: "Disenar regalos, etiquetas o camisetas personalizados usando proveedores que producen solo despues de vender.",
    potential: "Permite probar disenos antes de comprar maquinaria; requiere nicho y muestras atractivas para no competir solo por precio.",
    trend: "Los productos visuales se descubren en video corto y redes, pero necesitan diferenciacion y margen real.",
    skills: ["hands", "digital"],
    format: ["digital", "both", "home"],
    devices: ["phone", "internet"],
    budgetMin: 25,
    professionalBudget: 650,
    hoursMin: 8,
    risk: "medium",
    difficulty: "Inicial a intermedia",
    launch: "7-14 dias",
    automation: 60,
    extra: true,
    scalable: false,
    revenue: { units: 25, price: 14, unitCost: 8, fixed: 22 },
    clients: "Familias para celebraciones, pequenos comercios y eventos escolares.",
    investment: ["Tres muestras con proveedor local: USD 20-45", "Fotos y catalogo: USD 0-10", "Maquina propia solo tras volumen sostenible"],
    tools: ["Editor visual sencillo", "Proveedor de impresion o sublimacion", "Catalogo social", "Hoja de margenes"],
    process: ["Elige nicho concreto, por ejemplo regalos para graduacion.", "Cotiza tres proveedores y pide muestras.", "Publica preventa con fecha limite.", "Reinvierte solo si el margen y recompra lo justifican."],
    suppliers: "Talleres de impresion y sublimacion de la ciudad o plataformas bajo demanda disponibles en el pais; verificar envio y calidad.",
    branding: { names: ["Marca Momento", "Tu Dia Impreso", "Detalle Vivo"], slogan: "Un recuerdo hecho para esa persona.", colors: "Terracota, crema y carbon" },
    automationIdeas: ["Formulario de personalizacion", "Plantillas reutilizables", "Programacion de publicaciones"],
    errors: ["Comprar maquinaria al inicio", "Usar marcas o personajes sin permiso", "Subestimar envios y devoluciones"],
    growth: ["Colecciones estacionales", "Ventas empresariales", "Evaluar produccion propia con volumen"],
    comparable: "Modelos similares: tiendas de regalos personalizados por preventa y print-on-demand regional."
  }
];

window.BUSINESS_EVIDENCE = [
  { title: "Future of Jobs Report 2025", source: "World Economic Forum", use: "IA, cuidado, educacion y transformacion laboral hasta 2030", url: "https://www.weforum.org/reports/the-future-of-jobs-report-2025/" },
  { title: "Digital 2025 Global Overview", source: "DataReportal", use: "Descubrimiento movil, redes y compra digital", url: "https://datareportal.com/reports/digital-2025-global-overview-report" },
  { title: "Responses API", source: "OpenAI", use: "Planes estructurados y herramientas de tendencia en fase conectada", url: "https://platform.openai.com/docs/api-reference/responses/create" }
];
